name: Close Issue on Status Done Label

on:
  issues:
    types: [labeled]

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue if Status is Done
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.issue;
            const isDone = github.event.issue.labels.some(
              label => label.name === 'Status: Done'
            );

            if (isDone) {
              await github.rest.issues.update({
                ...issue,
                state: 'closed'
              });
            }
