name: Close Issue on Status Done Label

on:
  issues:
    types: [labeled]

jobs:
  close_issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Status: Done'
    steps:
      - name: Close Issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            })
